// P2/angular-test/src/app/character/character.component.ts
import { Component, OnInit } from '@angular/core';
import {GotService} from '../services/got.service';
import {ActivatedRoute} from '@angular/router';

@Component({
  selector: 'app-character',
  templateUrl: './character.component.html',
  styleUrls: ['./character.component.css']
})
export class CharacterComponent implements OnInit {
  public ready = false;
  public character;
  constructor (private got: GotService, private activeRouter: ActivatedRoute) {

    this.got.getACharacter(this.activeRouter.snapshot.params.id)
      .then((character: any) => {
        this.character = character.data;
        this.ready = true;
      });
  }

  ngOnInit() {


  }

}

<div class="padding">
  <button mat-raised-button [routerLink]="['']">Volver</button>


  <div class="padding">

    <mat-progress-spinner *ngIf="!ready" mode="indeterminate"></mat-progress-spinner>
    <div *ngIf="ready">
      <mat-card>
        <mat-card-header>
          <mat-card-title>{{ character?.name }}<sup><small> ({{ character?.slug }})</small></sup></mat-card-title>
        </mat-card-header>

        <mat-card-content>
          <h4>Ranking # {{ character?.pageRank}}</h4>
        </mat-card-content>
      </mat-card>
      <mat-card>

        <mat-card-header>
          <mat-card-title>Libros</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list role="list">
            <mat-list-item role="listitem" *ngFor="let book of character?.books">{{ book }}</mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
      <mat-card>

        <mat-card-header>
          <mat-card-title>Títulos Nobiliarios</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <mat-list role="list">
            <mat-list-item role="listitem" *ngFor="let title of character?.titles">{{ title }}</mat-list-item>
          </mat-list>
        </mat-card-content>
      </mat-card>
    </div>

  </div>
</div>

// P2/vue-test/src/components/Character.vue
<template>





  <div>


    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <span class="navbar-brand mb-0 h1">Personaje</span>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <router-link class="nav-link" to="/">Volver</router-link>

          </li>
        </ul>
      </div>
    </nav>


    <div v-show="isLoading" class="text-center">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>

    <div v-show="!isLoading">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ character.name }} ({{ character.slug}})<sup>#{{ character.pageRank }}</sup></h5>
          <p class="card-text">
            <span v-if="character.male"> Sexo: {{ character.male ? 'Hombre': 'Mujer' }} </span>
            <br>
            Casa: {{ character.house }}
          </p>
        </div>


        <ul class="list-group list-group-flush">
          <li class="list-group-item" style="background-color: #fafafa; color: blue;">TITULOS</li>
        </ul>
        <ul class="list-group list-group-flush" v-for="title in character.titles">
          <li class="list-group-item">{{ title }}</li>
        </ul>

        <ul class="list-group list-group-flush">
          <li class="list-group-item" style="background-color: #fafafa; color: blue;">LIBROS</li>
        </ul>
        <ul class="list-group list-group-flush" v-for="book in character.books">
          <li class="list-group-item">{{ book }}</li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script scoped>


  import { getACharacter } from '../services/got.service.js'
  export default {
    name: 'Character',
    data () {
      return {
        character: {},
        isLoading: false
      }
    },
    created () {
      this.isLoading = true
      const { id } = this.$route.params
      getACharacter(id)
        .then(res => {
          this.character = res.data
          this.isLoading = false
        })
    },
    methods: {
    }
  }
</script>
